### ISSUE TITLE
Currencies showing loading (NULL) due to URL Error

### ISSUE THREAD

**Issue by loggerheads-with-binary** [Dudebaker/Gadgets-Additions#1]
Hi, I have been using the facility for the past few days and I realize that there is this error specifically. 

Currencies are looked over ```https://www.cnbc.com/quotes/?symbol={Whatever Currency}``` . Seems they have changed this URL to ```https://www.cnbc.com/quotes/?symbol={Whatever Currency}=``` now. Thus it keeps showing loading even though practically everything else is the same. I tried changing the ```currencies.ini``` file, but to no avail. Would suggest looking into it.

**Comment by Dudebaker** [comment]
Hi,
which currencies did you try?
All I've pre-configurated seem to work, beside from USD->CAD, this has to be changed to "CAD=".

![image](https://user-images.githubusercontent.com/2338122/103638699-8b1de380-4f4d-11eb-87f1-5fc5123424bb.png)

**Comment by Dudebaker** [comment]
If any issue was there, then it should be fixed with v4.3.0
