### ISSUE TITLE
Incorrect timezone in cryptocurrencies widget

### ISSUE THREAD

**Issue by sparxnet000** [Dudebaker/Gadgets-Additions#3]
Rainmeter 4.4.0.3433 beta (64-bit)
Language: English (1033)
Build time: 2021-02-11 20:36:28
Windows 10 Home Single Language 2009 64-bit (build 19042) - English (1033)
GadgetsAddition 4.3.1

Issue: In the cryptocurrencies widget, the time of last refresh displayed is inaccurate. There is a 1 hour difference in the time shown and the current time.

I'm in India (UTC + 05:30)

Is there some place to specify the correct timezone or any way to "offset" this correctly ?

At 15:30 local time, the widget is showing updated at 16:30 (and so on...)

All currency prices are displaying accurately.

**Comment by Dudebaker** [comment]
Thanks for the info - will have to take a look at this, having the same behavior here (UTC+1).
Maybe the latest rainmeter beta has here some issues with the Timezone Daylight Bias.

A quick fix would be to go to the following file:
`C:\Users\**_USERNAME_**\Documents\Rainmeter\Skins\Gadgets Additions\@Resources\Templates\Time.ini`
And  change the formula:
From:
`Formula=(([MeasureTimeZone:] + [MeasureTimeZoneDayLight:]) * 60 * -1)`
To:
`Formula=([MeasureTimeZone:] * 60 * -1)`

**Comment by juhavt** [comment]
I had to completely disable the time zone measurement with `Formula=(60 * -1)` to get the right time for the RSS Reader.

**Comment by sparxnet000** [comment]
> And change the formula:
> From:
> `Formula=(([MeasureTimeZone:] + [MeasureTimeZoneDayLight:]) * 60 * -1)`
> To:
> `Formula=([MeasureTimeZone:] * 60 * -1)`

That worked for me. Thank Goodness, India doesn't have any Daylight Savings Time at all.

Thanks for the workaround, mate. Excellent work on the suite.
