### ISSUE TITLE
Currencies and Stocks meters aren't working

### ISSUE THREAD

**Issue by Shade-Of-Fear** [Dudebaker/Gadgets-Additions#4]
Hello, I've recently installed Gadgets.Additions_4.3.1.rmskin and found that the Currencies and Stocks meters aren't working. The Cryptocurrencies however are working.

All of the currencies and stocks stay on 0 and they have labels "loading". Clicking on the labels leads me to the correct https://www.cnbc.com page in my web browser.

In Rainmeter > About > Log I can see the below errors:

For the Currencies meter:

`ImageName: Unable to open: C:\Users\USERNAME\Documents\Rainmeter\Skins\Gadgets Additions\@Resources\Images\Currencies\.png (Gadgets Additions\Currencies\Currencies.ini)`

For the Stocks meter:

`(Fetch error) An error occurred in the secure channel support  (ErrorCode=12157) (Gadgets Additions\Stocks\Stocks.ini - [MeasureMarket2])`

**Comment by Dudebaker** [comment]
Hey,
currently they are working properly.
As the error on the stocks meter says, it has something to do with the ssl/tls connection.
Something was wrong with your connection to cnbc - there's nothing I can do.

**Comment by Shade-Of-Fear** [comment]
Hello, it's been a while, but I'd like to write my findings here, in case someone gets the same errors.
Indeed the issue was with my Windows 7 OS.

In short - Windows 7 supports TLS1.2, but doesn't support cipher suite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 which is required by cnbc.com.

As per my understanding the WebParser measure uses Windows API (Internet Explorer), and therefore uses the SSL/TLS and cipher suites, which are configured in the Windows registry.

There is no way to add the above cipher suite to the Windows 7 registry and make it work, therefore, as long as any Rainmeter Skin (Gadget) requires internet access to a page, requiring more secure protocols, Windows 7 users are out of luck.

**Comment by Dudebaker** [comment]
Thx for your investigation!
Then we have no luck with win7 - would have to find another source which doesn't require these cipher suits
