### ISSUE TITLE
ErrorCode=12057,  Cryptocurrencies

### ISSUE THREAD

**Issue by Cosmits** [Dudebaker/Gadgets-Additions#5]
LogFile  in   Rainmeter 

CoinGecko offline (Gadgets Additions\Cryptocurrencies\Cryptocurrencies.ini)

(Fetch error) Не удалось подключиться к серверу отзыва сертификатов, либо не был получен определенный ответ.  (ErrorCode=12057) (Gadgets Additions\Cryptocurrencies\Cryptocurrencies.ini - [MeasureCoinGeckoStatus])

**Comment by Dudebaker** [comment]
No issues in my installation.
Since the Status-Measure is shown, it shouldn't have to do anything with the coins you've entered.
Maybe restart rainmeter or your computer.

**Comment by Cosmits** [comment]
Im  update Rainmeter to  4.5.16.3687, but not work 
Win 10 Pro
CryptocurrenciesAlternative.ini  - also not work 

in browser  link    https://api.coingecko.com/api/v3/coins/
and https://api.cryptonator.com/api/ticker/btc-usd
work is very well

**Comment by Dudebaker** [comment]
Cryptonator requires a captcha even in the API - so we cannot do anything with Rainmeter, will be removed in the future versions.

CoinGecko is working perfectly fine on my side, even with Windows 11 and the same Rainmeter-Version.
Tested on multiple Locations (Home, Office, Friend, ...), all can show the crypto currencies in Rainmeter.

The issue has to be on your side or your PC.
If Rainmeter cannot even connect, I cannot help your.
